# Jekyll Configuration

url: http://michael.nona.name #XXX
title: Michael Chen's Blog #XXX
description: World in my view is a word of my view #XXX
author: Michael Chen #XXX
email: mechiland@gmail.com #XXX
analytics_id: UA-199699-1 #Google Analytics ID : UA-xxx-xxx  

lsi: false
port: 4000
markdown: kramdown
permalink: /:title
kramdown:
   input: GFM