# Jekyll Configuration

url: http://mechiland.github.com #XXX
title: Michael Chen's Blog #XXX
description: World in my view is a word of my view #XXX
author: Michael Chen #XXX
email: mechiland@gmail.com #XXX
analytics_id: UA-199699-7 #Google Analytics ID : UA-xxx-xxx  

auto: false
lsi: false
pygments: false
server_port: 4000
markdown: maruku
permalink: /archives/:title

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex
