# Jekyll Configuration

url: https://chenjinzhou.com #XXX
title: Michael Chen's Blog #XXX
description: World in my view is a word of my view #XXX
author: Michael Chen #XXX
analytics_id: UA-199699-1 #Google Analytics ID : UA-xxx-xxx

theme: minima
plugins:
  - jekyll-feed
lsi: false
markdown: kramdown
permalink: /:title
